# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Breww' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Breww
  pod 'Alamofire', '~> 4.7'
  pod 'AlgoliaSearch-Client-Swift'
  pod 'ALCameraViewController'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'SearchTextField'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'JGProgressHUD'
  
end
